### ISSUE TITLE
Plugin ID Mismatch

### ISSUE THREAD

**Issue by Hashemian01** [esm7/obsidian-rtl#1]
I keep getting "Plugin ID Mismatch" when i try to install this plugin. My obsidian version is v0.9.11

**Comment by esm7** [comment]
This seems to come from Obsidian's internals but I can't figure out why. As a shot in the dark, maybe I used something in the plugin that is incompatible with Obsidian 0.9.11 (I used 0.9.12). I'll try to investigate more thoroughly early next week, but hopefully 0.9.12 will be formally released by then and maybe it will solve the issue.

**Comment by esm7** [comment]
P.S: just in case, please try to delete the directory `VAULT_ROOT/.obsidian/obsidian-rtl` if you have it, then restart Obsidian and retry to install.

**Comment by ramisedhom** [comment]
@esm7 thanks for this plugin.

I also use v0.9.11 and had same issue. I also tried to download the plugin zip and decompress it into `VAULT_ROOT/.obsidian/obsidian-rtl` but it's not working.

Appreciate if this issue can be resolved soon.

**Comment by ramisedhom** [comment]
Ok, I believe the issue that the released file is not for "Obsidian RTL". It is for "Obsidian Vimrc Support".
Here is what I found in `manifest.json` file:
```
{
  "id": "obsidian-vimrc-support",
  "name": "Obsidian Vimrc Support",
  "version": "0.1.0",
  "description": "Auto-load a startup file with Obsidian Vim commands.",
  "author": "esm",
  "authorUrl": "",
  "isDesktopOnly": false
}

**Comment by esm7** [comment]
Great catch, sorry for the confusion! I fixed the release, please let me know if it works now.

**Comment by ramisedhom** [comment]
Installed, activated and switching LTR<>RTL successfully.
Thanks for your fast support.
