### ISSUE TITLE
Conflict with my custom CSS on Obsidian

### ISSUE THREAD

**Issue by BaselQq** [esm7/obsidian-rtl#12]
After i add the rtl plugin is my obsidian custom css  returned automaticly to the standard. But i want my custom css and not the standard one

Photos:
My custom CSS:
![image](https://user-images.githubusercontent.com/73541125/105617036-10bde200-5ddc-11eb-93f6-2887fcfa64a2.png)

The known standard one:
![image](https://user-images.githubusercontent.com/73541125/105617044-31863780-5ddc-11eb-8558-097f22d9e25e.png)

thanks in advance

**Comment by esm7** [comment]
Can you try to delete or move away `styles.css` from your plugin directory (under `VAULT/.obsidian/plugins/obsidian-rtl` or something along this line) and see if it solves the problem as a workaround?

**Comment by BaselQq** [comment]
Hey esm7! Thank you for your answer
It did not work, sorry!
I have tried so many possibilities. I don't think the problem comes from the styles.css file, but from the other manifest.json or main.js

**Comment by BaselQq** [comment]
I got my Obsidian CSS File from this link if u wanna see it:
https://github.com/BryanJenksCommunity/FAQ/discussions/2

**Comment by esm7** [comment]
Version 0.0.9 treats custom stylesheets more nicely now, so if this issue is still relevant, I'd love another look.

**Comment by BaselQq** [comment]
Your Update worked well. There are no issues left. Ty so much!
