### ISSUE TITLE
Lists don't work well in RTL

### ISSUE THREAD

**Issue by esm7** [esm7/obsidian-rtl#13]
Bullets are misplaced, nesting doesn't work.

**Comment by mr-islam** [comment]
I was trying to fix this, and making a small CSS snippet with the below did the job:

    pre.HyperMD-list-line {
	    text-indent: 0px !important;
    }

And it looks like this:

![rtl indent](https://user-images.githubusercontent.com/17675428/116003191-6f327080-a616-11eb-84ae-252551dcc2ef.png)

---

I would like to make a pull request, but I don't really know how Obsidian extensions are made / where to put this in the repo 😅

**Comment by esm7** [comment]
That's great and I'd love to get it integrated (also see https://github.com/esm7/obsidian-rtl/pull/14). Does it work for both the editor and preview?

**Comment by mr-islam** [comment]
Sorry, this was only for the editor not the preview (I forgot the preview mode exists)

But PR #14 looks like a much better solution honestly. My snippet above was just from clicking around in the dev tools for a few minutes

**Comment by esm7** [comment]
Thank you, I'll try to combine these to something consistent & useful for all scenarios :)

**Comment by esm7** [comment]
Fixed in 0.0.6!

**Comment by mr-islam** [comment]
Amazing, thank you!
