### ISSUE TITLE
rtl-title

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [esm7/obsidian-rtl#15]
I think matching “TITLE” in RTL/LTR position with body-text would be very nice aesthetically.
![image](https://user-images.githubusercontent.com/82666844/115046016-427eaa80-9eec-11eb-90ef-d67700cb08d4.png)

**Comment by esm7** [comment]
I'll happily give it a try! Hopefully it will work out ok with the rest of the UI.

**Comment by esm7** [comment]
Released 0.0.6 which adds this feature.
