### ISSUE TITLE
Support for Obsidian mobile

### ISSUE THREAD

**Issue by Amichayg** [esm7/obsidian-rtl#16]
Right now it seems the plugin doesn't work in Obsidian mobile, in edit and in preview mode.

**Comment by esm7** [comment]
That's right. Obsidian Mobile uses the next-gen CodeMirror 6 editor, which has a completely rewritten (and seemingly much better) RTL support. But I didn't get to review or integrate its API yet.
Will get to it as soon as I manage!

**Comment by esm7** [comment]
It's more than an issue, it requires to understand and rewrite the core functionality of this plugin (including many of the patches of various small behaviors) for a completely new API that works very differently.
It's important to me and I'll surely get to it, I just have very little free time lately :(

**Comment by jrykner** [comment]
still not supported on mobile, despite update to new version that supports live preview?

**Comment by esm7** [comment]
You are definitely correct that the fact we now have the plugin working with CM6 is a major step (maybe even 90% of the work) towards making it work on mobile. But unfortunately it's not an automatic conversion. The editor in the mobile app is wrapped differently than in Obsidian 0.13.14 and requires some tinkering different from the desktop app, that I didn't get to investigate yet.

**Comment by esm7** [comment]
I completed the adjustments needed to support Obsidian Mobile and it now works in the just-released 0.3.0 version!
