### ISSUE TITLE
Preview pane RTL

### ISSUE THREAD

**Issue by IronMG** [esm7/obsidian-rtl#2]
Hi, 
First of all, your rtl plugin is what makes obsidian relevant for me (after the horror that is the new Evernote update) - so thank you! 
I think RTL support for the preview pane can be really great, for me anyway, if you ever get around to it.

(hope I'm posting this in the right place - I'm very new here)

Thanks,
Iron

**Comment by esm7** [comment]
Thanks, that's definitely the right place. Preview pane RTL is in my short-term todo list, will do my best to get to it soon.

**Comment by IronMG** [comment]
That sounds great, thank you!

Iron

**Comment by GodFatherMK** [comment]
Hi. 
I just want to thank you for the RTL Plugin for Obsidian.
but please add RTL feature to the Preview Pane in Obsidian.
I really need this feature and waiting for it.
thanks again.

**Comment by viaahmed** [comment]
Yeah, I am also waiting for that.
Thanks for the plugin.

**Comment by GodFatherMK** [comment]
> Thanks, that's definitely the right place. Preview pane RTL is in my short-term todo list, will do my best to get to it soon.

Can your RTL Plugin work in other obsidian places like outline view in the right panel?
I'm Still waiting for the preview RTL Mode.

Thanks in advance.

**Comment by esm7** [comment]
I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.

**Comment by IronMG** [comment]
Awesome!

I will, thanks.

Iron

**Comment by GodFatherMK** [comment]
> I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.

I was waiting for this Update.

Thanks a bunch.

 I have tested it and Preview Pane RTL works like a charm. (Obsidian 0.9.20)

By the way RTL Doesn't work in Outline menu on the right panel of Obsidian.

Please Continue your support for this Awesome Plugin.

**Comment by GodFatherMK** [comment]
> I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.

I was waiting for this Update.

Thanks a bunch.

 I have tested it and Preview Pane RTL works like a charm. (Obsidian 0.9.20)

By the way RTL Doesn't work in Outline menu on the right panel of Obsidian.

Please Continue your support for this Awesome Plugin.


> I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.

One more Request. RTL Doesn't Work in link preview popup, Please Correct this too.
Thanks in advance.

**Comment by GodFatherMK** [comment]
One irrelevant question:

When I type Shift + Space (Semi-Space) in Obsidian with Persian (Right to Left) Keyboard Layout in edit mode, It creates a red dot character and when I hover my mouse on this red dot, it says \u200c.

This red dot (\u200c) distract me.

Is there a way to hide this red dot (\u200c)، Character in edit mode?

**Comment by esm7** [comment]
> > I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.
> 
> I was waiting for this Update.
> 
> Thanks a bunch.
> 
> I have tested it and Preview Pane RTL works like a charm. (Obsidian 0.9.20)
> 
> By the way RTL Doesn't work in Outline menu on the right panel of Obsidian.
> 
> Please Continue your support for this Awesome Plugin.
> 
> > I published a new version 0.0.3 with preview pane RTL, please upgrade and let me know how it works for you.
> 
> One more Request. RTL Doesn't Work in link preview popup, Please Correct this too.
> Thanks in advance.

I'm afraid that I won't be able to keep up on my own with adding RTL support to all the possible views of Obsidian, especially when there are still major usability issues with RTL like https://github.com/esm7/obsidian-rtl/issues/7 and https://github.com/esm7/obsidian-rtl/issues/6.
It will help me if you open a separate issue for this, so I can get a sense of how many users want these features and be able to invest the time wisely :)

Regarding what you mentioned with Shift+Space, I suggest to try the CodeMirror [BIDI demo](https://codemirror.net/demo/bidi.html) and see if it happens there too. It is most likely a CodeMirror behavior and the best route might be to open an issue there.
