### ISSUE TITLE
Incompatibility with Excalidraw

### ISSUE THREAD

**Issue by zsviczian** [esm7/obsidian-rtl#20]
@yuvve recorded the following issue for Excalidraw: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/124
I was able to reproduce the error. I looked at your source code. Based on my quick scan I would try adding 

```typescript
let view = this.app.workspace.getActiveViewOfType(MarkdownView);
if (!view) return;
```

to [here](https://github.com/esm7/obsidian-rtl/blob/6a0e2627bdc67b006c3cb60e7a23cc007736a37b/main.ts#L142)

I am not really sure if this will solve the problem, but it seems you make modifications to the document object even if the view is not a markdown view: see [here](https://github.com/esm7/obsidian-rtl/blob/6a0e2627bdc67b006c3cb60e7a23cc007736a37b/main.ts#L153)

**Comment by esm7** [comment]
Indeed, this code is ancient and needs some urgent renewal, it actually even precedes Obsidian's formal API...
I'll make the needed adjustments and test them as soon as I get the chance.

**Comment by esm7** [comment]
Fixed.
The issue was eventually in the very hacky way the plugin overwrote `@media print` style rules for the purpose of RTLing exports. It's still way more hacky than I'd want, but it's now far more selective and doesn't interfere with Excalidraw.
Also, just for the heck of it I also added better checking for the view type before making these overwrites.

**Comment by SH20RAJ** [comment]
🚀 Need a better way to visualize ideas & collaborate? Check out SketchFlow – an AI-powered whiteboard for brainstorming, planning, and designing with ease! 🎨🤖 With real-time collaboration, infinite canvas, and smart object recognition, it's perfect for developers, designers, and teams. And it’s free! Try it now: https://sketchflow.space/ 🚀 #SketchFlow #AIWhiteboard
