### ISSUE TITLE
YAML RTL

### ISSUE THREAD

**Issue by Alexnoj** [esm7/obsidian-rtl#25]
Can you add option change direction of YAML to RTL?

**Comment by esm7** [comment]
Just released 0.1.0 which added configurable support for this. It's not as generic as I wanted, but it's half way there.

**Comment by RoqaiaRF** [comment]
@esm7  cool ! how can i now use the rtl 
i want to change this content to RTL :

code (index.md)  : 
`---
layout: home
title: توثيق الانظمة
titleTemplate: قسم الانظمة والدعم الفني
    
hero:
  name:  توثيق الانظمة
  text:  قسم الانظمة والدعم الفني

  tagline: تجد هنا كل ما تحتاجه لحل مشاكلك في القسم
  actions:
    - theme: brand
      text: ابدأ من هنا
      link: /home
    - theme: alt
      text: رابط المشروع
      link: https://github.com/RoqaiaRF/docs
  # image:
  #   src: /images/logo.png

features:
  - icon: 📝
    title: انغمس في دروس أنظمة تكنولوجيا المعلومات
    details: امتحن نفسك في دليل شامل لأنظمة مختلفة داخل قسم تكنولوجيا المعلومات. قم بإنشاء وثائق مفصلة بسهولة تبسط المفاهيم المعقدة.
    
  - icon: 💻
    title: استكشف مزايا تكنولوجيا المعلومات
    details: اكتشف تجربة تكنولوجيا المعلومات الاستثنائية مع إطلاق الأنظمة السريعة والتحديثات السريعة والتكامل السلس للوحدات الإضافية المتقدمة.

  - icon: ☑️
    title: تخصيص بالابتكار
    details: أضف الابتكار إلى وثائقك. ادمج بنية ومكونات Vue مباشرة أو قم بإنشاء سمات فريدة باستخدام Vue لعرض الأنظمة بأسلوبك الخاص.

  - icon: 🚀
    title: استمتع بفهم سريع
    details: سهل فهم المعقدات. حقق فهمًا سريعًا من خلال شروحات مباشرة، مما يضمن فهمًا سهلاً لأنظمة تكنولوجيا المعلومات المعقدة.
---
<style>
:root {
  --vp-home-hero-name-color: transparent;
  --vp-home-hero-name-background: -webkit-linear-gradient(120deg, #BDBDBD 30%, #6699cc);

  --vp-home-hero-image-background-image: linear-gradient(-45deg, #BDBDBD 50%, #ebedf3 50%);
  --vp-home-hero-image-filter: blur(40px);
}

@media (min-width: 640px) {
  :root {
    --vp-home-hero-image-filter: blur(56px);
  }
}

@media (min-width: 960px) {
  :root {
    --vp-home-hero-image-filter: blur(72px);
  }
}
</style>`
