### ISSUE TITLE
Support for live preview mode

### ISSUE THREAD

**Issue by Amichayg** [esm7/obsidian-rtl#26]
The Live Preview mode that is currently in the insider build doesn't support the RTL Plugin. It looks like a pretty important feature for obsidian, so RTL support for this feature should be pivotal moving forward.

**Comment by esm7** [comment]
Live preview will probably become the default choice for most users at some point, so I'll definitely expand the RTL plugin to support it as soon as I get the chance.

**Comment by esm7** [comment]
Updated the plugin for live preview (version 0.2.0), have fun :)
