### ISSUE TITLE
Community Plugins Description Page

### ISSUE THREAD

**Issue by Hashemian01** [esm7/obsidian-rtl#28]
Changing direction in a page, affects community plugins description page as well

![image](https://user-images.githubusercontent.com/48093461/147453801-496e7a86-653a-42d2-b4db-5739c6a5428e.png)

**Comment by esm7** [comment]
That's definitely an annoying bug, it requires more more selective patching of the Markdown preview style than the plugin is currently doing.
It means that there's also an issue if there are multiple displayed panes that some are RTL and some are LTR.

**Comment by esm7** [comment]
Fixed (along most other known bugs) in the just-released 0.3.0!
