### ISSUE TITLE
Toogle the horizontal cursor movement

### ISSUE THREAD

**Issue by ramisedhom** [esm7/obsidian-rtl#3]
Obsidian v0.9.15
OS: Windows 10
Obsidian RTL Plugin v0.0.1

**Steps**
1. Open file
2. Press Ctrl+P and select "RTL Support: Switch Text Direction (LTR<>RTL)"
3. File switch direction to RTL but cursor move still from left-to-right

**Expected behavior**
It's expected to toggle the horizontal cursor movement to be right-to-left as well.

**Further analysis**
As per [CodeMirror User Manual](https://codemirror.net/doc/manual.html), option 'rtlMoveVisually' control the horizontal cursor movement. Its default value is 'false' on Windows.

**Suggestion**
To add few lines to toggle 'rtlMoveVisually' along with the file 'direction' option.

**Comment by esm7** [comment]
Should be fixed now but I don't have Windows to test it, please update to 0.0.2 and let me know.

**Comment by Ronsharo** [comment]
When you say "Open file" which file do you mean? And how do I open it? - Soryy, Im a newbe...

**Comment by esm7** [comment]
@Ronsharo these directions relate to recreating the bug, which is hopefully not relevant anymore.

**Comment by ramisedhom** [comment]
@esm

> 
> 
> Should be fixed now but I don't have Windows to test it, please update to 0.0.2 and let me know.

Thanks @esm7 very much for such fast support, I had updated the plugin to v0.0.2 and it works fine, except 1 small issue, pressing keyboard {Home} go to end of line and pressing keyboard {End} go to beginning of line. Is this reproducible at your end?

**Comment by Ronsharo** [comment]
Oh I see...

Can you by any chance recommend a right to Left support plugin for obsidian?


Thanks,
Ron.

**Comment by Ronsharo** [comment]
Can you send me a link for the download?

**Comment by ramisedhom** [comment]
@Ronsharo :

1. From Obsidian, go to "Settings" > "Third-party plugins",
2. Switch off "Safe mode" and click on "Community plugins" > "Browse",
3. Find plugin "RTL Support" and click "Install"

**Comment by esm7** [comment]
> @esm
> 
> > Should be fixed now but I don't have Windows to test it, please update to 0.0.2 and let me know.
> 
> Thanks @esm7 very much for such fast support, I had updated the plugin to v0.0.2 and it works fine, except 1 small issue, pressing keyboard {Home} go to end of line and pressing keyboard {End} go to beginning of line. Is this reproducible at your end?

It happens to me too! I didn't notice it previously.
It seems to be an Obsidian behavior and not CodeMirror, I'll see if I can patch around it.
I opened a separate issue for this: https://github.com/esm7/obsidian-rtl/issues/6

**Comment by Ronsharo** [comment]
Thanks a lot. Cant find community plugins...

[image: image.png]

**Comment by Ronsharo** [comment]
Oh got it now.

**Comment by Ronsharo** [comment]
O.k which file do I open here and how do I open it?

**Comment by Ronsharo** [comment]
It works great.Thank you
