### ISSUE TITLE
Plugin not working at all (v0.13.19)

### ISSUE THREAD

**Issue by tomerganz** [esm7/obsidian-rtl#30]
First of all I would like to thank you very much for this great plugin, it really helped me for over a year!
I'm not sure what's causing this, but for some reason the plugin stopped working completely.
I downgraded to v0.13.14 of obsidian, only then, combined with the older v0.1.0 of this plugin, did it return to working order.
For now I'll use the older versions, but am I missing something?

**Comment by esm7** [comment]
There is a bug that I'm aware of, that didn't get around to fix, and maybe that's the issue you're experiencing. In the newer Obsidian and the latest version of the plugin, either use the new editor (not the legacy one), or as a temporary workaround if you wanna keep the old editor, turn on the new editor just once, restart Obsidian, then turn off the new editor and restart Obsidian again.
Let me know if this worked, meaning it's the same issue I'm aware of.

**Comment by tomerganz** [comment]
Updated everything and used the new editor, no dice.
I noticed this: files that were already in RTL were flipped once I pressed the hotkey, either in preview or live preview, and then got locked in LTR. Hope it helps you find the cause!

**Comment by esm7** [comment]
1. Can you open the Obsidian Developer Console (Ctrl+Shift+I) and copy & paste any logs you see there?
2. What version of Obsidian and the plugin are you using right now?

**Comment by tomerganz** [comment]
![image](https://user-images.githubusercontent.com/85462894/151152190-0abeb9e8-930d-4905-91e6-3eda605c1e1a.png)
I hope I'm looking at the right place.
Obsidian -  v0.13.19, Plugin v0.2.0

**Comment by esm7** [comment]
I just released a fix that might be relevant.
1. Can you update the plugin and check if it helps, and if not, paste your debug console the same way you did before?
2. Also, I'm scratching my head trying to understand what you mean by "files that were already in RTL were flipped once I pressed the hotkey, either in preview or live preview, and then got locked in LTR". Do you mean that some files are properly displayed as RTL, but when you switch to LTR, you can't switch back to RTL?
3. Are you using a custom theme? If so, can you try to temporarily turn it off (get back to Obsidian's default theme), restart Obsidian and see if it changes anything?

**Comment by tomerganz** [comment]
Firstly, thanks for all the help and support! I greatly appreciate it
I updated the plugin(0.2.1), stayed on v0.13.19 of obsidian.
I'm sorry for my very unclear explanation, I only got that just now, but somehow you understood me perfectly!

I can explain the behavior I'm observing now, after the update and using the default theme:
1. The LTR<->RTL switching only works in CM5 mode **while in editing view**, but even if the file was in RTL in editing view, it shows up in preview as LTR. You can see by the title direction it should be RTL (it does change direction when I press the hotkey, but the file itself stays LTR)
![image](https://user-images.githubusercontent.com/85462894/151716260-9e77f3ab-3109-4fd3-9ad0-e3da6cc5484c.png)

![image](https://user-images.githubusercontent.com/85462894/151716263-71f159f8-1313-4f57-8ef4-3249a4add0e6.png)

2. When I relaunch into CM6, the same RTL file is shown as RTL in both preview and live preview, but as soon as I press the hotkey, it switches to LTR and stays that way. No errors are shown in the console even after pressing the hotkey a few times.

![image](https://user-images.githubusercontent.com/85462894/151716314-440891d7-8882-4a8f-b82d-28a4a22273c5.png)

![image](https://user-images.githubusercontent.com/85462894/151716328-d4d00c9d-fe52-4837-a6a2-2a9006d37cf2.png)
(Won't flip back to RTL, no errors showing up)
Hope it helps. 

For now, I'm reverting to v0.13.4 and plugin v0.1.0 using the legacy editor, for some reason it's still working.

**Comment by esm7** [comment]
That is very clear and I think I have what I need to track down the issue (later this week when I get a few hours to work on it). Thank you!
And BTW, it's a pleasure to see your beautiful usage of Obsidian & RTL, especially in live preview! Hope you'll have it fully working in a few days.

**Comment by esm7** [comment]
I found the issue and believe to have fixed it, you should be able to upgrade and use live preview now. Let me know how it works for you.

**Comment by tomerganz** [comment]
Updated everything (Obsidian and the plugin) and everything works perfectly!
Awesome work. Thank you very very much.
