### ISSUE TITLE
Suggestion: Use dir="auto" HTML attributes on a paragraph level

### ISSUE THREAD

**Issue by lingdocs** [esm7/obsidian-rtl#31]
Thanks so much for your good work with this plugin. I don't know the details of how this all integrates with CodeMirror but may I suggest adding [`dir="auto"` attributes](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) to all the paragraph tags? In all my years of working with LTR-RTL this seems to be the simplest and robust solution for me. A lot of people would like to see [auto LTR-RTL support on a paragraph level](https://forum.obsidian.md/t/rtl-support/1438/54?u=lingdocs) and this [one little html attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) takes care of that perfectly.

```html
<p dir="auto">This paragraph is in English and goes right to left.</p>
<p dir="auto">هذه الفقرة باللغة العربية ، لذا يجب الانتقال من اليمين إلى اليسار.</p>
```

Boom. Renders the first paragraph LTR and the second paragraph RTL. No punctuation issues either.

**Comment by esm7** [comment]
Hey, I really wish this could work but unfortunately it's far more problematic than that. CodeMirror is not just a text box, it's a huge piece of code that manipulates and displays text, with complex abstractions and APIs that allow all the goodies that you see in Obsidian and other editors.
Even if you can force its generated HTML to add `dir="auto"`, nothing good will come out of it. The entire behavior will be wrong, inconsistent and overall extremely buggy.
I'd love to see auto LTR-RTL on the paragraph level but the only way to make this happen is to write this support as part of CodeMirror.
