### ISSUE TITLE
Direction parameter affects all visible notes

### ISSUE THREAD

**Issue by Limezy** [esm7/obsidian-rtl#33]
Hi, thanks again for that awesome plugin, and thanks for implementing the yaml direction thing, so useful for me !
I have a problem since the new version, which is that now the direction affects all visible notes. All notes will take the direction saved for the highlighted note (see screenshot video below)
I'm pretty sure this wasn't the case before ?

https://user-images.githubusercontent.com/24638389/163216114-8d018ca0-e1b1-4384-8eb2-0f3b25605bab.mov

Thanks for your help !

**Comment by esm7** [comment]
Indeed the switch to the new editor required some adaptations that have proven to be very buggy.
I need to massively redo some of how the plugin works and hoping to find time for that soon enough.

**Comment by esm7** [comment]
Fixed (along most other known bugs) in the just-released 0.3.0!

**Comment by Limezy** [comment]
Yeah !
