### ISSUE TITLE
Settings window is affected when in RTL mode

### ISSUE THREAD

**Issue by ma-sadeghi** [esm7/obsidian-rtl#36]
# Settings window, when an RTL document is active

![image](https://user-images.githubusercontent.com/14086031/174126699-c227355c-9565-481a-b843-9b1479c73424.png)

# Settings window, when an LTR document is active

![image](https://user-images.githubusercontent.com/14086031/174126855-f05869fe-222d-455f-b844-3fcf660675db.png)

**Comment by esm7** [comment]
Fixed (along most other known bugs) in the just-released 0.3.0!
