### ISSUE TITLE
Problem in Rendering Checklists and lists 

### ISSUE THREAD

**Issue by pourmand1376** [esm7/obsidian-rtl#49]
I just include the pictures. I think they are clear enough. I have to mention that I don't change anything except RTL model. 

LTR mode:
![image](https://user-images.githubusercontent.com/32064808/209482192-81fd758a-b516-45a9-ad48-e872ae76a58a.png)

RTL mode:
![image](https://user-images.githubusercontent.com/32064808/209482199-03b70675-ccc4-4ee2-bb75-2936e6c93d00.png)

This is a common issue for me. But the odd thing is that only sometimes it gets problematic. For the same markdown file, if I close and reopen the file for multiple times, It finally solves by itself.

**Comment by yamanidev** [comment]
have you found a solution to this?

**Comment by yamanidev** [comment]
@esm7 thank you for the fast reply!

Obsidian: v1.5.12
RTL Support plugin: 0.3.0

It seems that my plugin is way old, I didn't realize that I had to manually re-install to update. Is there a way to automatically update these plugins?

**Comment by yamanidev** [comment]
I just did that, but it did not fix the alignment issues.

I just noticed the option on the bottom left bar that configures the language direction, it was set to LTR, I changed it back to auto and now it's working.

Thanks!

![image](https://github.com/esm7/obsidian-rtl/assets/65856786/9419b81e-5235-4805-a353-fc4e4076064e)
