### ISSUE TITLE
Skipping a word stops at the character before the last.

### ISSUE THREAD

**Issue by mhaj98** [esm7/obsidian-rtl#5]
When using CTRL + Left/Right arrow (i.e. skipping a word) the cursor stops at the character before the last of the new word

**Comment by esm7** [comment]
Please check if this also happens in the CodeMirror [BIDI demo](https://codemirror.net/demo/bidi.html).
It is probably the way CodeMirror behaves in RTL.

**Comment by esm7** [comment]
I verified and indeed this is a CodeMirror issue. Please [open a bug there](https://github.com/codemirror/CodeMirror/issues), it will contribute to many RTL-enabled products :)
