### ISSUE TITLE
Add support for Syriac script/ language.

### ISSUE THREAD

**Issue by AliKhomami** [esm7/obsidian-rtl#56]
Hello, thank you for developing this plugin. It is very useful for working with different scripts and languages.

I have a problem with using the plugin in Auto Mode with the Syriac script.
When I type or paste a Syriac text in Auto Mode, I expect it to change the direction to RTL automatically, but it doesn’t. It works fine with Arabic and Hebrew scripts but not with Syriac.

Could you please add support for the Syriac script to your plugin? Thank you very much for your time and attention.
![image](https://user-images.githubusercontent.com/15670700/225021846-7e3f1871-db60-4595-94a7-865c2a153f65.png)

**Comment by zoli** [comment]
For this getting fixed I think it only needs to move `\p{sc=Syriac}` from second group to first group in [this line](https://github.com/esm7/obsidian-rtl/blob/master/globals.ts#L8).

**Comment by esm7** [comment]
@AliKhomami for the purpose of testing this, would you mind commenting here with some Syriac text?

**Comment by zoli** [comment]
- Thaana
- Syriac

Are the two that are on the second group that should go to first one I think.

**Comment by AliKhomami** [comment]
> @AliKhomami for the purpose of testing this, would you mind commenting here with some Syriac text?

`ܘܐܢܫ̈ܝܢ ܐܡܪܝܢ ܕܐܟܙܢܐ ܩܕ݂ܡܝܬ݂ ܪܟܒ ܐܬܘ̈ܬܐ ܥܒܪ̈ܝܬܐ ܘܒܗܝܢ ܣܡ ܢܡܘܣܐ ܆ ܗܟܢܐ ܘܫܝܠܡܘܢ ܪܟܒ ܐܬܘ̈ܬܐ ܕܣܦܪ̈ܐ ܐܚܪ̈ܢܐ ܘܝܗ݂ܒ ܠܥܡ̈ܡܐ ܕܐܬܝܩܪ ܡܢܗܘܢ ܂ ܘܩܕܡܝܬ ܕܣܘܪܝܝܐ ܗ̇ܘ ܕܝܗܒ ܠܚܝܪܡ ܕܨܘܪ`

**Comment by esm7** [comment]
Fixed and released an updated version.
