### ISSUE TITLE
Broken UI on tags

### ISSUE THREAD

**Issue by NitzanHen** [esm7/obsidian-rtl#57]
Hi!

First of all, I'd like to say I deeply appreciate your continuing effort on this plugin - it's great. Thank you!

The UI for obsidian tags seems to break when this plugin is on. For example:
![image](https://user-images.githubusercontent.com/58311807/227782529-6f84e10d-9c51-42fe-94d5-8d4c7a1fd8e3.png)

The root of the problem seems to be in the CSS classes `.cm-hashtag-begin` and `.cm-hashtag-end`. The first goes on the hash tag and the latter on the text itself, which works as intended on LTR text, but breaks when writing RTL.
These classes are associated with the following styles:
![image](https://user-images.githubusercontent.com/58311807/227782617-f11bf8dd-9855-4588-829d-0aca693e86ea.png)
(styles for `.cm-hashtag-end` are declared similarily).

If I understand correctly, in RTL these two should be flipped - either by or overriding them to replace the right/left rules, switching the CSS classes themselves. 

(I'd argue the first option is a more correct solution, if it's possible - the names `begin` and `end` make sense for the hashtag and the text respectively).

What do you think?

Again, thank a lot!

**Comment by esm7** [comment]
Are you using the latest version of the plugin (1.1.1)? It is supposed to include a fix for that (https://github.com/esm7/obsidian-rtl/issues/54).

**Comment by NitzanHen** [comment]
Apparently, I was not (had 1.1.0 installed instead). 
Updated and the bug is not fixed. Many thanks!
