### ISSUE TITLE
Broken on 1.5?

### ISSUE THREAD

**Issue by cool-RR** [esm7/obsidian-rtl#66]
I recently upgraded Obsidian to 1.5.3. Now RTL seems to be broken. All notes are LTR and when I invoke the command, it does nothing. Has anyone else experienced this?

**Comment by esm7** [comment]
Please try to update the plugin to its latest version (1.1.2), which is meant exactly to fix this problem, and report back.

**Comment by cool-RR** [comment]
Well butter my biscuits, it worked. I thought these updates were automatic, but I guess it makes sense they're manual. Thank you!

**Comment by esm7** [comment]
In this case it's quite a problematic mechanism, because the plugin has no way of informing the users they need to update :(
