### ISSUE TITLE
[FR] Dynamic (Per line/paragraph depending on the language you type) RTL/LTR support

### ISSUE THREAD

**Issue by chromer030** [esm7/obsidian-rtl#69]
This Feature can be adapted from https://github.com/mwxgaf/obsidian-dynamic-rtl

**Comment by esm7** [comment]
It was implemented long ago, use a recent version of the plugin and switch
to auto mode.

**Comment by chromer030** [comment]
It seems that something is wrong with my .md file, after transfering all notes to new file, it solved.
Thanks very much.
