### ISSUE TITLE
Issues with auto-pair brackets in RTL

### ISSUE THREAD

**Issue by esm7** [esm7/obsidian-rtl#7]
When in RTL mode, the Obsidian "Auto pair brackets" feature doesn't work well.
When entering an opening bracket (e.g. opening parenthesis), the cursor ends up after the closing bracket instead of between the brackets. This does not happen when typing the same thing in LTR.
I don't know yet where auto-pairing is implemented (Obsidian/CodeMirror) and where the bug belongs, but maybe this plugin can work around it.

**Comment by esm7** [comment]
I reported the bug in CodeMirror and it was fixed immediately: https://github.com/codemirror/CodeMirror/issues/6527

**Comment by mr-islam** [comment]
Amazing, thank you for your great work on this plugin and also to track down the issue!

So to get this patch from CodeMirror, we must wait for the entire Obsidian app to update the CodeMirror version, right?

**Comment by esm7** [comment]
We need to wait for CodeMirror to release a version and then for Obsidian to update their CM version. In the meantime I'm making a temporary workaround in the plugin that disables the bracket auto-close feature when in RTL.

**Comment by esm7** [comment]
Patched in the new release (0.0.4), auto-pair is now off in RTL and back as configured in LTR.
