### ISSUE TITLE
Mixed LTR/RTL support

### ISSUE THREAD

**Issue by ma-sadeghi** [esm7/obsidian-rtl#73]
Is it possible to add support for mixed LTR/RTL? This [plugin](https://github.com/OpenMindAmir/obsidian-dynamic-rtl) implements it, but it's been deprecated.

**Comment by esm7** [comment]
It's supported in Obsidian RTL for over a year.
Just switch to Auto direction mode, which can be configured in the plugin settings to be the default.

**Comment by ma-sadeghi** [comment]
Works like a charm, amazing! Thanks!
