### ISSUE TITLE
Mixed PDF export

### ISSUE THREAD

**Issue by yonatankremer** [esm7/obsidian-rtl#74]
[Test rtl.pdf](https://github.com/esm7/obsidian-rtl/files/14624588/Test.rtl.pdf)

Using the built-in pdf export command (or any other one) doesn't handle files with both rtl and ltr lines in it at all. In the editor itself it works fine <img width="427" alt="Screenshot 2024-03-16 at 9 55 01 AM" src="https://github.com/esm7/obsidian-rtl/assets/133390605/7c941182-210b-434d-aa6d-9e9aeec100f6">

**Comment by esm7** [comment]
Shouldn't happen and it recreates for me too. Seems like it broke in one of the recent versions, will investigate.

**Comment by esm7** [comment]
Should be fixed in 1.2.1, please let me know if it works for you.

**Comment by yonatankremer** [comment]
it does. tysm
