### ISSUE TITLE
Messing up Persian Sentences Containing (Bold - Italic- Strikethrough and coded ) English Phrases

### ISSUE THREAD

**Issue by Wnb369** [esm7/obsidian-rtl#77]
Hi,

I've been experiencing an issue after updating Obsidian or the plugin.

The issue is that when I bold, italicize, strikethrough, an English word or writing a code before an English word or phrase in the middle of a Persian sentence, the text gets messed up in the preview mode.
![Capture1](https://github.com/esm7/obsidian-rtl/assets/130536416/54fd6b18-3143-487d-a031-05c34e2de8b2)

The strange thing is that this bug didn't exist before, and even if I copy and paste my previous writing into a new note, the problem doesn't occur. However, everything gets messed up with newly typed text, as shown in the image above.
I'm not using any custom themes or CSS code.
Thank you again for all your hard work and dedication🌱.

**Comment by esm7** [comment]
That's incredibly odd.
1. It does not happen at Editing Mode at all, right? The issue is only with Reading Mode?
2. Can you paste here an example text that causes the issue, preferably a couple of lines?

**Comment by zoli** [comment]
This problem is rooted in my last PR ([this line](https://github.com/esm7/obsidian-rtl/pull/72/files#diff-e9a6bf3a51fc03d4cba0a27c79e8010492e6a48570415993cfd2807fe9ad56afL109)).

We need tests to prevent this kind of breaking changes. I will write some tests and fix this issue afterward.

**Comment by Wnb369** [comment]
> That's incredibly odd.
> 
> 1. It does not happen at Editing Mode at all, right? The issue is only with Reading Mode?
> 2. Can you paste here an example text that causes the issue, preferably a couple of lines?

Yes, this issue only occurs in reading mode.
 I appreciate your time in advance.
 
![Capture99](https://github.com/esm7/obsidian-rtl/assets/130536416/69ed3aa0-0ade-4101-ad6e-d8f94dfdc14f)

**Comment by Wnb369** [comment]
> This problem is rooted in my last PR ([this line](https://github.com/esm7/obsidian-rtl/pull/72/files#diff-e9a6bf3a51fc03d4cba0a27c79e8010492e6a48570415993cfd2807fe9ad56afL109)).
> 
> We need tests to prevent this kind of breaking changes. I will write some tests and fix this issue afterward.

Thank you Zoli for your time and effort in always trying to solve problems.
 Many of the things you do are helpful for making Obsidian easier to work with, and I am really grateful for that. Tashakor🙏🏼

**Comment by mrostd** [comment]
I updated the plugin today, but there is a problem when you want to use lists, for example:
- این یک **test** است.![Screenshot_20240513-191152_Obsidian.png](https://github.com/esm7/obsidian-rtl/assets/53259265/ca8794d2-4952-4b31-80d1-6e4594e13a8b)

![Screenshot_20240513-191050_Obsidian.png](https://github.com/esm7/obsidian-rtl/assets/53259265/97418321-9dce-44f5-b010-47b9acbfd663)

**Comment by esm7** [comment]
Obsidian is about to include native mixed RTL support in version 1.6.0 and it will solve this issue. There is no need to continue working it as part of the RTL plugin.

**Comment by esm7** [comment]
I agree, but it's an unrelated feature (I don't think it's part of 1.6.0 yet, it will probably be released in the upcoming days for catalysts).
The mixed RTL support will be available regardless of the interface languages, just like the RTL plugin does.
