### ISSUE TITLE
Bullet point locked in ltr mode 

### ISSUE THREAD

**Issue by Ske-Man1149** [esm7/obsidian-rtl#84]
Note : In windows version 

=> ![IMG-20240629-WA0000](https://github.com/esm7/obsidian-rtl/assets/128849789/148ab122-66f0-4a4d-83ea-1ac9faf4808b)

**Comment by esm7** [comment]
Can you elaborate:
1. Which version of the plugin?
2. Which version of Obsidian?
3. Is the note defined as LTR/RTL/Auto?
4. Is the Obsidian UI in LTR or RTL mode?
5. Any custom themes used?

A screenshot of the whole Obsidian window can give some of these as context too.

**Comment by Ske-Man1149** [comment]
@esm7 
Ok,firstly thank your respond
Secondly

**Comment by esm7** [comment]
Even if it's irrelevant, would you mind sharing what it was, in case other users run into it?

**Comment by Ske-Man1149** [comment]
@esm7 Sorry, I closed it by mistake

**Comment by Ske-Man1149** [comment]
1. Which version of the plugin? => 2.0.0  
2. Which version of Obsidian? => 1.6.5
3. Is the note defined as LTR/RTL/Auto? => RTL
4. Is the Obsidian UI in LTR or RTL mode? => LTR
5. Any custom themes used? => prism 
note on (5) : I enabled the default theme and the bug is still in.

**Comment by Ske-Man1149** [comment]
# CSS Snippet 
```
.markdown-preview-view.is-rtl ul,
.markdown-preview-view.is-rtl ol {
    direction: rtl;
    text-align: right;
    list-style-position: inside;
}
.markdown-preview-view.is-rtl ul li,
.markdown-preview-view.is-rtl ol li {
    direction: rtl;
    text-align: right;
    list-style-position: inside;
}
.markdown-preview-view.is-rtl .list-bullet {
    float: right;
    margin-right: -12px;
}
.markdown-preview-view.is-rtl li > ul::before,
.markdown-preview-view.is-rtl li > ol::before {
    left: auto;
    right: -15px;
}

```

**Comment by esm7** [comment]
Note that this is an Obsidian bug, not an Obsidian-RTL plugin problem, and it will be fixed in the next Obsidian release.

**Comment by Ske-Man1149** [comment]
@esm7 I would like to say thank you for everything, without you I would not have been able to start my journey in Obsidian (hats off to you, buddy) .
